services:
  yaf:
    image: fidelismachine/shadowmeter:latest
    container_name: yaf
    restart: unless-stopped      
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_nice
    environment:
      # For live capture, set the following the the monitoring interface
      - SHADOWMETER_INTERFACE=${SHADOWMETER_INTERFACE}  
      # Or, for offline PCAP analysis, set the followint to the path of` 
      # a file with a list of PCAP files, one per line
      # - SHADOWMETER_PCAP_LIST=${SHADOWMETER_PCAP_LIST}
    volumes:
      - ./var/shadowmeter/spool:/var/shadowmeter/spool
    command: /opt/shadowmeter/scripts/entrypoint-yaf.sh

  super_mediator:
    image: fidelismachine/shadowmeter:latest
    container_name: super_mediator
    restart: unless-stopped  
    volumes:
      - ./var/shadowmeter/spool:/var/shadowmeter/spool
    depends_on:
      - yaf      
    command: /opt/shadowmeter/scripts/entrypoint-super_mediator.sh

  shadowmeter:
    image: fidelismachine/shadowmeter:latest
    container_name: shadowmeter
    restart: unless-stopped   
    environment:
      - SHADOWMETER_ID=${SHADOWMETER_ID}   # arbitrary label
      - SHADOWMETER_DATABASE=${SHADOWMETER_DATABASE}
    volumes:
      - ./var/shadowmeter/spool:/var/shadowmeter/spool
    depends_on:
      - questdb
      - super_mediator       
    command: /opt/shadowmeter/scripts/entrypoint-shadowmeter.sh
    
  questdb:
    image: questdb/questdb
    container_name: questdb
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./var/questdb:/root/.questdb
    environment:
      - QDB_HTTP_ENABLED=true                  # NOTE: set this to true to enable the HTTP interface on port 9000
      - QDB_LOG_W_STDOUT_LEVEL=ERROR
      - QDB_LOG_W_FILE_LEVEL=ERROR
      - QDB_LOG_W_HTTP_MIN_LEVEL=ERROR
      - QDB_SHARED_WORKER_COUNT=2               # Amount of worker threads
      - QDB_PG_USER=${SHADOWMETER_USERNAME}     # postgresql user -> Configured in .env file
      - QDB_PG_PASSWORD=${SHADOWMETER_PASSWORD} # postgresql password -> Configured in .env file
      - QDB_TELEMETRY_ENABLED=false             # Disable telemetry
      - QDB_HTTP_SECURITY_READONLY=true
      - QBD_LINE_UDP_ENABLED=true
      - QDB_HTTP_MIN_ENABLED=true

  shadowmeter_app:
    image: fidelismachine/shadowmeter_app:latest
    container_name: shadowmeter_app
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./var/grafana:/var/lib/grafana
    # uncomment below to enable custom provisioning
    #- ./grafana/provisioning:/etc/grafana/provisioning

  shadowmeter_nginx:
    image: fidelismachine/shadowmeter_nginx:latest
    container_name: shadowmeter_nginx
    restart: unless-stopped 
    volumes:
      - ./var/log/nginx:/var/log/nginx
      # uncomment below to enable signed certificates
      #- ./ssl.crt:/etc/nginx/ssl.crt
      #- ./ssl.key:/etc/nginx/ssl.key      
  
    ports:
      - 80:80/tcp
      - 443:443/tcp  
    depends_on:
      - shadowmeter_app
