services:
  yaf:
    image: fidelismachine/shadowmeter:latest
    container_name: yaf
    restart: unless-stopped      
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_nice
    environment:
      - SHADOWMETER_INTERFACE=${SHADOWMETER_INTERFACE}  
    volumes:
      - ./var/shadowmeter/spool:/var/shadowmeter/spool
    command: /opt/shadowmeter/scripts/entrypoint-sm_yaf.sh

  sm_import:
    image: fidelismachine/shadowmeter:latest
    container_name: sm_import
    restart: unless-stopped   
    environment:
      - SHADOWMETER_OBSERVATION_ID=${SHADOWMETER_OBSERVATION_ID}   # observatin domain label
    volumes:
      - ./var/shadowmeter/spool:/var/shadowmeter/spool  
      - ./var/maxmind:/var/maxmind:ro          
    depends_on:
      - questdb 
    command: /opt/shadowmeter/scripts/entrypoint-sm_import.sh
    
  sm_export:
    image: fidelismachine/shadowmeter:latest
    container_name: sm_export
    restart: unless-stopped   
    environment:
      - SHADOWMETER_DB_URI=questdb:9009
    volumes:
      - ./var/shadowmeter/spool:/var/shadowmeter/spool
    depends_on:
      - questdb 
    command: /opt/shadowmeter/scripts/entrypoint-sm_export.sh

  questdb:
    image: questdb/questdb
    container_name: questdb
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./var/questdb:/root/.questdb
    environment:
      - QDB_HTTP_ENABLED=true                  # NOTE: set this to true to enable the HTTP interface on port 9000
      - QDB_LOG_W_STDOUT_LEVEL=ERROR
      - QDB_LOG_W_FILE_LEVEL=ERROR
      - QDB_LOG_W_HTTP_MIN_LEVEL=ERROR
      - QDB_SHARED_WORKER_COUNT=2               # Amount of worker threads
      - QDB_PG_USER=${SHADOWMETER_USERNAME}     # postgresql user -> Configured in .env file
      - QDB_PG_PASSWORD=${SHADOWMETER_PASSWORD} # postgresql password -> Configured in .env file
      - QDB_TELEMETRY_ENABLED=false             # Disable telemetry
      - QDB_HTTP_SECURITY_READONLY=true
      - QBD_LINE_UDP_ENABLED=true
      - QDB_HTTP_MIN_ENABLED=true

