#
#
#

export LIBTORCH=${PWD}/../../libtorch
export LIBTORCH_INCLUDE=${LIBTORCH}/include
export LIBTORCH_LIB=${LIBTORCH}
export LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH
#export LIBTORCH_BYPASS_VERSION_CHECK=1



